# Generated by Django 2.0 on 2017-12-05 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_SKU', models.IntegerField(max_length=6)),
                ('item_name', models.CharField(max_length=70)),
                ('item_unit_price', models.IntegerField(max_length=5)),
                ('item_retail_price', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SalesAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainboard.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.IntegerField(max_length=4)),
                ('store_name', models.CharField(max_length=100)),
                ('store_region', models.CharField(max_length=70)),
                ('store_address', models.TextField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='salesadvice',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainboard.Stores'),
        ),
    ]
