# Generated by Django 2.0 on 2017-12-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='item_SKU',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='item_retail_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='item_unit_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stores',
            name='store_code',
            field=models.IntegerField(),
        ),
    ]
