# Generated by Django 2.0 on 2017-12-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0002_auto_20171205_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='store_code',
            field=models.CharField(max_length=4),
        ),
    ]
