# Generated by Django 2.0 on 2017-12-05 04:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mainboard', '0003_auto_20171205_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Stores',
            new_name='Store',
        ),
    ]
    atomic = False
