# Generated by Django 2.0 on 2017-12-07 05:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0004_auto_20171205_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAdviceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='salesadvice',
            name='item',
        ),
        migrations.AddField(
            model_name='salesadvice',
            name='adviceCreateDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesadvice',
            name='adviceCreator',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesadvice',
            name='adviceEditDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesadvice',
            name='adviceEditor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesadvice',
            name='invoiceNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesadviceitems',
            name='invoiceNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainboard.SalesAdvice'),
        ),
        migrations.AddField(
            model_name='salesadviceitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainboard.Product'),
        ),
    ]
