# Generated by Django 2.0 on 2017-12-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0005_auto_20171207_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesadvice',
            name='invoiceNumber',
            field=models.CharField(default='ABC000000', max_length=20),
        ),
    ]
