# Generated by Django 2.0 on 2017-12-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0007_salesadvice_invoicedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesadviceitems',
            name='itemQty',
            field=models.IntegerField(default=0),
        ),
    ]
