# Generated by Django 2.0 on 2017-12-07 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0009_auto_20171207_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesadvice',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainboard.Store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
