# Generated by Django 2.0 on 2017-12-10 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0012_auto_20171207_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesadvice',
            name='paymentDueDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesadvice',
            name='totalAmtPayable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesadvice',
            name='totalItemQty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesadviceitems',
            name='itemCost',
            field=models.IntegerField(default=0),
        ),
    ]
