# Generated by Django 2.0 on 2017-12-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0013_auto_20171210_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesadvice',
            name='adviceStatus',
            field=models.CharField(default='FOR APPROVAL', max_length=50),
        ),
    ]
