# Generated by Django 2.0 on 2017-12-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0014_salesadvice_advicestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesadvice',
            name='adviceEditDate',
            field=models.DateField(null=True),
        ),
    ]
