# Generated by Django 2.0 on 2017-12-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0015_auto_20171214_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesadviceitems',
            name='itemUnitCost',
            field=models.IntegerField(default=0),
        ),
    ]
