# Generated by Django 2.0 on 2017-12-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0016_salesadviceitems_itemunitcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_retail_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_unit_price',
            field=models.FloatField(),
        ),
    ]
