# Generated by Django 2.0 on 2017-12-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0017_auto_20171219_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesadviceitems',
            name='itemCost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salesadviceitems',
            name='itemUnitCost',
            field=models.FloatField(default=0),
        ),
    ]
