# Generated by Django 2.0 on 2017-12-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0018_auto_20171219_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesadvice',
            name='invoiceNumber',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
