# Generated by Django 2.0 on 2017-12-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0019_auto_20171220_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptNumber', models.CharField(default='', max_length=20, unique=True)),
            ],
        ),
    ]
