# Generated by Django 2.0 on 2017-12-20 07:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0021_receivingadviceitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivingadvice',
            name='adviceCreateDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receivingadvice',
            name='adviceCreator',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receivingadvice',
            name='adviceEditDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='receivingadvice',
            name='adviceEditor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receivingadvice',
            name='receiptDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receivingadvice',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainboard.Store'),
            preserve_default=False,
        ),
    ]
