# Generated by Django 2.0 on 2017-12-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0023_receivingadvice_advicestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivingadviceitems',
            name='itemCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receivingadviceitems',
            name='itemUnitCost',
            field=models.IntegerField(default=0),
        ),
    ]
