# Generated by Django 2.0 on 2017-12-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainboard', '0024_auto_20171222_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivingadviceitems',
            name='itemCost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='receivingadviceitems',
            name='itemUnitCost',
            field=models.FloatField(default=0),
        ),
    ]
